function [S, wavelen] = loadSPEfiles(mask, Ns);
%[S, wavelen] = loadSPEfiles(mask)
%
%This function loads spectra from a series of ASCII files generated by
%WinSpec32 software.

S = [];
if (nargin == 1)
    files = dir(mask);
    if isempty(files) 
        error('No files found!');
    end;
    names = cell(1, length(files));
    for i = 1:length(files);
        names{i} = files(i).name;
    end;
end;

if (nargin == 2)
    names = cell(1,length(Ns));
    for i = 1:length(Ns);
        names{i} = sprintf(mask, Ns(i));
    end;
end;

for i = 1:length(names);
    buf = load(names{i});
    S = [S buf(:,2)];
    %disp(sprintf('File %s loaded.', names{i}));
end;

wavelen = buf(:,1);
